[package]
name = "slint-snake"
version = "0.1.0"
edition = "2024"

[dependencies]
slint = { version = "1.8.0", features = ["backend-winit"] }
log = "0.4"
env_logger = "0.11.8"
rand = "0.9.1"

[build-dependencies]
slint-build = "1.8.0"